Tenancy cleanup
SchulichRacingElectrical/srv-database-ms pull request #12
Opened 2022-04-19 23:29 UTC by Tijunel

Basically added tenancy/auth rules to endpoints as needed. Added a bunch of other endpoints for auth and user, did cleanup where I could. Error handling and tenancy if-else mess could probably use a cleanup in the future with some tenant assert functions, we should review next time we see each other.

2022-04-25 12:39 UTC, arhamHumayun approved these changes, later dismissed

2022-05-04 02:50 UTC, justinf34 commented on app/models/operator.model.go
> +	ID 							primitive.ObjectID 		`json:"_id,omitempty" bson:"_id,omitempty"`
Could we format this?

2022-05-04 03:16 UTC, justinf34 requested changes

2022-05-04 03:16 UTC, justinf34 commented on app/models/sensor.model.go
> +	UpperCalibration     float64           	`json:"upperCalibration,omitempty" bson:"upperCalibration,omitempty"`
I think if we don't set this as a pointer then a 0 value would be considered empty and this not be able to input zeros in the database

2022-05-04 03:16 UTC, justinf34 commented on app/models/thing.model.go
>  	ID        				primitive.ObjectID   `json:"_id,omitempty" bson:"_id,omitempty"`
Could we format this file?

2022-05-04 03:16 UTC, justinf34 commented on app/models/thing_operator.model.go
> +	ID						primitive.ObjectID		`json:"_id,omitempty" bson:"_id,omitempty"`
Could we format this file?

2022-05-04 03:16 UTC, justinf34 commented on utils/errors.go
>  	EntityCreationError 	= "entityCreationError"
Could we format this file?

2022-05-04 16:55 UTC, Tijunel commented on app/models/sensor.model.go
> +	UpperCalibration     float64           	`json:"upperCalibration,omitempty" bson:"upperCalibration,omitempty"`
Good catch.

2022-05-04 16:57 UTC, Tijunel commented on app/models/sensor.model.go
> +	UpperCalibration     float64           	`json:"upperCalibration,omitempty" bson:"upperCalibration,omitempty"`
Actually no, we don't want to insert the element at all in the database if it does not get posted or put. Found this out the hard way. This way, the fields do not exist in the db if they are not put in.

2022-05-05 19:22 UTC, justinf34 approved these changes

2022-05-05 19:24 UTC, merged