Implementing Auth, User Signup and Login
SchulichRacingElectrical/srv-database-ms pull request #9
Opened 2022-02-28 21:54 UTC by arhamHumayun

Implemted:
- Admin API key. This grants admin permissions on all endpoints
- User Login endpoint. On successful signup a JWT token is saved as a cookie with user id.
- User Signup endpoint.

Auth/Middleware:
- First checks for Admin API key. If it is present and matching, admin permissions are granted via context.
- If not, it checks for a JWT token via an Authorization cookie. If this is successfully parsed the context is set to contain user info and org info.

Currently, endpoints do not check for specific permissions. This can be added in a later pull request.
Still need to create other basic user and organization endpoints such as update and delete.

2022-03-05 20:39 UTC, justinf34 requested changes

2022-03-05 20:39 UTC, justinf34 commented on app/handlers/model.handler.go
> +}
I don't think we need to create a struct res for each entity right now since they all send just the id. In PR #8 renamed `createSensorRes` to `createEntityRes` so that it can be used for any creating endpoint. So let us merge PR #8 first so that you can refactor this and the other files that use these structs

2022-03-05 20:39 UTC, justinf34 commented on app/handlers/organization.handler.go
> +// func (handler *OrganizationHandler) FindByOrganizationId(c *gin.Context) {
Should we delete these commented out functions? Are we going to implement them later?

2022-03-05 20:39 UTC, justinf34 commented on app/handlers/user.handler.go
> +
Should we check if users already exists?

2022-03-05 20:39 UTC, justinf34 commented on app/handlers/user.handler.go
> +		utils.Response(c, http.StatusBadRequest, result)
I think for login we should not send an error when the use inputs the wrong credentials, we should send a an object that indicates that log in failed.

2022-03-05 20:39 UTC, justinf34 commented on app/services/organization/organization.service.go
> +	// FindUpdatedOrganization(context.Context, string, int64) ([]*model.Organization, error)
We should delete unused methods

2022-03-06 01:45 UTC, arhamHumayun commented on app/handlers/user.handler.go
> +
Sure, I can add a check for an existing email.

2022-03-06 01:45 UTC, arhamHumayun commented on app/handlers/organization.handler.go
> +// func (handler *OrganizationHandler) FindByOrganizationId(c *gin.Context) {
I will implement some of them, and delete others.

2022-03-12 20:30 UTC, arhamHumayun commented on app/handlers/user.handler.go
> +		utils.Response(c, http.StatusBadRequest, result)
I now have it return a 401 (Status Unauthorized) code, with a wrong password message.

2022-03-12 21:01 UTC, arhamHumayun commented
Merged master into this branch, and addressed all conflicts.

2022-03-19 19:08 UTC, justinf34 approved these changes, later dismissed
LGTM! Please merge after the `auth.go` file has been reviewed

2022-03-19 19:18 UTC, Tijunel commented on app/handlers/organization.handler.go
> +		println("it aint real")
bruh

2022-03-19 19:45 UTC, Tijunel approved these changes

2022-03-19 19:45 UTC, merged